### ISSUE TITLE
Some examples in the README file are invalid

### ISSUE THREAD

**Issue by wajunye** [sbabcoc/Remote-Session#14]
Note: some methods in the readme file are marked "cannot resolve method".

ps: Thank you for providing such a tool. It works well with me.

**Comment by wajunye** [comment]
offer you the stars ^.^

**Comment by sbabcoc** [comment]
Hi, @wajunye ! I'm glad this library is working for you. Please provide details on the methods that can't be resolved and I'll see about making corrections.

**Comment by sbabcoc** [comment]
I think I finally figured out with class you were referring to. Some time ago, I'd deleted the **BatchUtils** class because I forgot why it was actually there in the first place. I just restore this class, fixing up the related README section and duplicating this text in the class-level JavaDoc header.
